### ISSUE TITLE
[Bug]: Code quality test doesn't works

### ISSUE THREAD

**Issue by NaturalSelect** [Async-Lab/CPP_project_1#6]
**描述Bug（Describe the bug）:**

代码质量测试无法工作。

`.github/customs/classTest.sh: line 3: ${{github.workspace}}: bad substitution`

**环境（Environment）:**

**如何重现（To Reproduce）:**

**期望的行为（Expected behavior）:**

**附加上下文（Additional context）:**

**Comment by NaturalSelect** [comment]
@WhereAreBugs

**Comment by WhereAreBugs** [comment]
I see, I will try to fix.
