### ISSUE TITLE
[Bug]: `functional_test` always timeout

### ISSUE THREAD

**Issue by NaturalSelect** [Async-Lab/CPP_project_1#8]
**描述Bug（Describe the bug）:**

功能测试总是超时，因为`Popen.communicate`等待进程结束。

**环境（Environment）:**

**如何重现（To Reproduce）:**

**期望的行为（Expected behavior）:**

**附加上下文（Additional context）:**

**Comment by NaturalSelect** [comment]
@WhereAreBugs

**Comment by WhereAreBugs** [comment]
我曾经尝试过使用重定向stdout的方式来接受预期的输出，但是会在程序调用clear清屏的时候和程序调用类似于按任意键继续之类的功能时例如(`system("read -n 1 -p \"Press any key to continue...\" INP");`)出现问题，因此我才采用这种形式。因此这个超时是预期中的，忘记注释掉这个输出了。

**Comment by NaturalSelect** [comment]
> 我曾经尝试过使用重定向stdout的方式来接受预期的输出，但是会在程序调用clear清屏的时候和程序调用类似于按任意键继续之类的功能时例如(`system("read -n 1 -p \"Press any key to continue...\" INP");`)出现问题，因此我才采用这种形式。因此这个超时是预期中的，忘记注释掉这个输出了。

可以在文档中说明这点禁止它调用清屏。

**Comment by WhereAreBugs** [comment]
确实也是可以的，只是现在改文档会不会有些太晚了，我这里的逻辑是只要程序能被kill掉检测也还是会通过的

**Comment by NaturalSelect** [comment]
> 确实也是可以的，只是现在改文档会不会有些太晚了，我这里的逻辑是只要程序能被kill掉检测也还是会通过的

也行，但是read超时需要大一点，避免被误判。

**Comment by WhereAreBugs** [comment]
好的，马上修改
