### ISSUE TITLE
[Bug]: code quality test doesn't works as expected

### ISSUE THREAD

**Issue by NaturalSelect** [Async-Lab/CPP_project_1#9]
**描述Bug（Describe the bug）:**

代码质量测试不会像预期一样工作，即使未使用`class`也会认为他使用了。

**环境（Environment）:**

**如何重现（To Reproduce）:**

**期望的行为（Expected behavior）:**

**附加上下文（Additional context）:**

**Comment by NaturalSelect** [comment]
@WhereAreBugs

**Comment by WhereAreBugs** [comment]
I see, I will fix it.
